#pragma once

#define LEN_BTNS(btns) (sizeof(btns) / sizeof(btns[0]))

#define SHUTTER_BTN_THRSH 600

#define BTN_BTMLEFT_SHFT (0)
#define BTN_BTMRIGHT_SHFT (2)
#define BTN_THUMB_SHFT (4)
#define BTN_TOPLEFT_SHFT (6)
#define BTN_TOPRIGHT_SHFT (8)

typedef enum
{
    RELEASED,
    HALF,
    FULL
} shutter_button_state_t;

typedef enum
{
    BTN_BL = 0,
    BTN_BR,
    BTN_THMB,
    BTN_TL,
    BTN_TR,
    BTN_SHTR
} button_t;

typedef enum
{
    BTN_STATE_LO = 0,
    BTN_STATE_HI,
    BTN_STATE_RISING,
    BTN_STATE_FALLING,
} button_state_t;

void buttons_main();
shutter_button_state_t shutter_button();

#define BTN_BTMLEFT_LO (BTN_STATE_LO << BTN_BTMLEFT_SHFT)
#define BTN_BTMLEFT_HI (BTN_STATE_HI << BTN_BTMLEFT_SHFT)
#define BTN_BTMLEFT_RI (BTN_STATE_RISING << BTN_BTMLEFT_SHFT)
#define BTN_BTMLEFT_FA (BTN_STATE_FALLING << BTN_BTMLEFT_SHFT)

#define BTN_BTMRIGHT_LO (BTN_STATE_LO << BTN_BTMRIGHT_SHFT)
#define BTN_BTMRIGHT_HI (BTN_STATE_HI << BTN_BTMRIGHT_SHFT)
#define BTN_BTMRIGHT_RI (BTN_STATE_RISING << BTN_BTMRIGHT_SHFT)
#define BTN_BTMRIGHT_FA (BTN_STATE_FALLING << BTN_BTMRIGHT_SHFT)

#define BTN_THUMB_LO (BTN_STATE_LO << BTN_THUMB_SHFT)
#define BTN_THUMB_HI (BTN_STATE_HI << BTN_THUMB_SHFT)
#define BTN_THUMB_RI (BTN_STATE_RISING << BTN_THUMB_SHFT)
#define BTN_THUMB_FA (BTN_STATE_FALLING << BTN_THUMB_SHFT)

#define BTN_TOPLEFT_LO (BTN_STATE_LO << BTN_TOPLEFT_SHFT)
#define BTN_TOPLEFT_HI (BTN_STATE_HI << BTN_TOPLEFT_SHFT)
#define BTN_TOPLEFT_RI (BTN_STATE_RISING << BTN_TOPLEFT_SHFT)
#define BTN_TOPLEFT_FA (BTN_STATE_FALLING << BTN_TOPLEFT_SHFT)

#define BTN_TOPRIGHT_LO (BTN_STATE_LO << BTN_TOPRIGHT_SHFT)
#define BTN_TOPRIGHT_HI (BTN_STATE_HI << BTN_TOPRIGHT_SHFT)
#define BTN_TOPRIGHT_RI (BTN_STATE_RISING << BTN_TOPRIGHT_SHFT)
#define BTN_TOPRIGHT_FA (BTN_STATE_FALLING << BTN_TOPRIGHT_SHFT)
