domain_path: /home/test/Projects/CameraZynq/camera_platform/export/camera_platform/sw/george
app_src_dir: /home/test/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/peripheral_tests
template: peripheral_tests
